@startuml
'https://plantuml.com/class-diagram

class Scraper{
+String listname
+float priceSold
+String date
+String hyperlink
+float dataP []
+float parseArr []
+filter()
+float pullPrice()
+getAvg()
+getCategory()
}

class Main {
+search()
+scraper()
}


interface Item{
String listname
String itemType()
}

class consumerGoods {
}

class foodAndBev {
}

class industrialGoods {
}

class services {
}

class digitalProducts {
}

class educationalGoods {
}

class healthcareGoods {
}

class HTML {
Search bar
Displays sorted data
New search button
}

Main --o Scraper
HTML --* Main

Item <|-- consumerGoods
Item <|-- foodAndBev
Item <|-- services
Item <|-- industrialGoods
Item <|-- educationalGoods
Item <|-- healthcareGoods
Item <|-- digitalProducts


Scraper o-- Item
Scraper --o HTML

@enduml
