@startuml
autonumber

actor Customer as user
participant SearchView
participant PriceScrapper
participant Filter
participant Calculation
participant SearchResult

user -> SearchView: enters URL of item
SearchView -> PriceScrapper: search()

PriceScrapper -> SearchView: getSelectedItem()
SearchView -> PriceScrapper: scrapper()
SearchView --> PriceScrapper: HTML Item elements

PriceScrapper -> Filter: filter()
Filter -> PriceScrapper: getListingName()
Filter -> PriceScrapper: getPriceSold()
Filter -> PriceScrapper: getDate()
Filter -> PriceScrapper: getLink()
PriceScrapper --> SearchResult: Name, Date, Link 

Filter -> Calculation: PriceCalc()
Calculation -> Filter: getAvg()
Filter --> Calculation: Average Price
Calculation -> Filter: pullPrice()

Filter --> SearchResult: Average Price
PriceScrapper -> SearchResult: ShowList()
note left: Code will run but can fail if the elements are not from ebay. \nIn other words, it will fail if it cannot connect to website
SearchResult --> SearchView: Price Estimate



@enduml
